spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gift_test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gift}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gift}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
