spring.application.name=gift
spring.jpa.open-in-view=false

# DataSource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:15432/gift_test
spring.datasource.username=gift
spring.datasource.password=gift
spring.jpa.hibernate.ddl-auto=update
kakao.message.token=ACCESS_TOKEN
kakao.message.url=https://kapi.kakao.com/v1/api/talk
kakao.social.token=ACCESS_TOKEN
kakao.social.url=https://kapi.kakao.com/v1/api/talk
