spring.application.name=gift
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

# Database (환경변수로 주입)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gift}
spring.datasource.username=${DB_USERNAME:gift}
spring.datasource.password=${DB_PASSWORD:gift}
kakao.message.token=ACCESS_TOKEN
kakao.message.url=https://kapi.kakao.com/v1/api/talk
kakao.social.token=ACCESS_TOKEN
kakao.social.url=https://kapi.kakao.com/v1/api/talk
