spring.datasource.url=jdbc:postgresql://localhost:15432/gift_test
spring.datasource.username=gift
spring.datasource.password=gift1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
